parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
  project: 'tsconfig.json'
plugins:
  - '@typescript-eslint/eslint-plugin'
extends:
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
env:
  node: true
root: true
rules:
  '@typescript-eslint/no-explicit-any': error
  '@typescript-eslint/explicit-module-boundary-types': error
  '@typescript-eslint/member-ordering':
    - error
    - default:
        - signature

        - public-static-field
        - protected-static-field
        - private-static-field
        - public-static-get
        - protected-static-get
        - private-static-get
        - public-static-set
        - protected-static-set
        - private-static-set
        - public-static-method
        - protected-static-method
        - private-static-method

        - public-decorated-field
        - protected-decorated-field
        - private-decorated-field
        - public-instance-field
        - protected-instance-field
        - private-instance-field
        - public-abstract-field
        - protected-abstract-field
        - private-abstract-field

        - public-decorated-get
        - protected-decorated-get
        - private-decorated-get
        - public-instance-get
        - protected-instance-get
        - private-instance-get
        - public-abstract-get
        - protected-abstract-get
        - private-abstract-get

        - public-decorated-set
        - protected-decorated-set
        - private-decorated-set
        - public-instance-set
        - protected-instance-set
        - private-instance-set
        - public-abstract-set
        - protected-abstract-set
        - private-abstract-set

        - public-constructor
        - protected-constructor
        - private-constructor

        - public-decorated-method
        - protected-decorated-method
        - private-decorated-method
        - public-instance-method
        - protected-instance-method
        - private-instance-method
        - public-abstract-method
        - protected-abstract-method
        - private-abstract-method
  curly:
    - error
    - all
  no-unused-vars: 'off'
  no-console: error
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/ban-types': 'off'
  import/no-named-as-default: off
  import/no-namespace: off
  import/namespace: off
  import/no-unresolved: off
  import/order:
    - error
    - groups:
        - type
        - object
        - internal
        - external
        - parent
        - sibling

      newlines-between: never
